VaccineSurvey.Web/Controllers/CategoriesController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using VaccineSurvey.Data.Repositories;
using VaccineSurvey.Model;

namespace VaccineSurvey.Web.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly IQuestionRepository questionRepository;

        public CategoriesController(IQuestionRepository questionRepository, ICategoryRepository categoryRepository)
        {
            this.questionRepository = questionRepository;
            this.categoryRepository = categoryRepository;
        }

        public async Task<ActionResult> Index()
        {
            ViewBag.Questions = await questionRepository.GetAllAsync();
            return View(await categoryRepository.GetAllAsync());
        }

        public ActionResult Create()
        {
            if (UserRoleDetails.GetLanguage() == "admin") return View();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Category viewModel)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (ModelState.IsValid)
                {
                    var Succeeded = await categoryRepository.CreateAsync(viewModel);
                    if (Succeeded)
                    {
                        TempData["Success"] = "Category saved successfully.";
                        return RedirectToAction("Create");
                    }
                }
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            var category = await categoryRepository.FindByIdAsync(id);
            if (category == null) { return RedirectToAction("Index"); }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Category viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            var Succeeded = await categoryRepository.UpdateAsync(viewModel, UserRoleDetails.GetLanguage());
            if (Succeeded)
            {
                TempData["Success"] = "Category Updated successfully.";
                return RedirectToAction("Edit", new { id = viewModel.Id });
            }

            return RedirectToAction("Edit", new { id = viewModel.Id });
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (id == null) { return RedirectToAction("Index"); }
                var category = await categoryRepository.FindByIdAsync(id);
                if (category == null) { return RedirectToAction("Index"); }
                return View(category);
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (id == null)
                {
                    TempData["Error"] = "Try again input data error";
                    return RedirectToAction("Index");
                }
                var Succeeded = await categoryRepository.DeleteAsync(id);
                if (Succeeded)
                {
                    TempData["Success"] = "Category deleted successfully";
                    return RedirectToAction("Index");
                }
                TempData["Error"] = "Try again input data error";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

VaccineSurvey.Web/Controllers/QuestionsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using VaccineSurvey.Data.Repositories;
using VaccineSurvey.Model;

namespace VaccineSurvey.Web.Controllers
{
    [Authorize]
    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();
        private readonly IQuestionRepository questionRepository;
        private readonly IOptionRepository OptionRepository;
        private readonly IFormInputRepository formInputRepository;
        private readonly ICategoryRepository categoryRepository;

        public QuestionsController(IQuestionRepository questionRepository, IFormInputRepository formInputRepository, ICategoryRepository categoryRepository, IOptionRepository OptionRepository)
        {
            this.OptionRepository = OptionRepository;
            this.questionRepository = questionRepository;
            this.formInputRepository = formInputRepository;
            this.categoryRepository = categoryRepository;
        }

        public async Task<ActionResult> Index(int? id)
        {
            IEnumerable<Question> questions = null;
            if (id != null && id > 0) { questions = await categoryRepository.GetQuestionsAsync(id); }
            if (questions != null && questions.Count() > 0) { }
            else { questions = await questionRepository.GetAllAsync(); }
            ViewBag.FormInputs = await formInputRepository.GetAllAsync();
            ViewBag.Options = await OptionRepository.GetAllAsync();
            ViewBag.ChildQuestions= await questionRepository.GetChildQuestion();
            return View(questions);
        }

        public async Task<ActionResult> Create(int? id)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                int categoryId = 0;
                if (id != null) { categoryId = (int)id; }
                ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", categoryId);
                ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName");
                var model = new Question
                {
                    IsRequired = true,
                    Sequence = 0
                };
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Question viewModel)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", viewModel.CategoryId);
                ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", viewModel.FormInputId);
                if (!ModelState.IsValid) { return View(viewModel); }
                var questionId = await questionRepository.CreateAsync(viewModel);
                if (questionId == 0)
                {
                    TempData["Error"] = "Try again input data error";
                    return RedirectToAction("Create", viewModel);
                }
                TempData["Success"] = "Question Saved successfully.";
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int? id, int? parentQuestionId)
        {
            if (id == null) { return RedirectToAction("Error"); }
            var model = await questionRepository.FindByIdAsync(id);
            if (model == null) { return RedirectToAction("Error"); }
            ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", model.FormInputId);
            ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", model.CategoryId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Question viewModel)
        {
            ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", viewModel.FormInputId);
            ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", viewModel.CategoryId);

            if (!ModelState.IsValid) { return View(viewModel); }
            var Succeeded = await questionRepository.UpdateAsync(viewModel, UserRoleDetails.GetLanguage());
            if (!Succeeded) { return RedirectToAction("Error"); }
            else { TempData["Success"] = "Question Updated successfully."; }
            return RedirectToAction("Edit", new { id = viewModel.Id });
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            var viewModel = await questionRepository.DetailsAsync(id);
            if (viewModel == null) { return RedirectToAction("Index"); }

            viewModel.ChildQuestions = await _context.Questions.Include(q => q.Children).Where(q => q.ParentId == id).ToListAsync();
            ViewBag.DataModel = viewModel;
            ViewBag.FormInputs = await formInputRepository.GetAllAsync();
            return View(new QuestionOption() { QuestionId = (int)id });
        }

        public async Task<ActionResult> Delete(int? id, int? parentQuestionId)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (id == null) { return RedirectToAction("Index"); }
                var viewModel = await questionRepository.FindByIdAsync(id);
                if (viewModel == null) { return RedirectToAction("Index"); }
                ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", viewModel.FormInputId);
                ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", viewModel.CategoryId);
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? Id, int? ParentQuestionId)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (Id == null) { return RedirectToAction("Index"); }
                var Succeeded = await questionRepository.DeleteAsync(Id);
                if (!Succeeded) { return RedirectToAction("Index"); }
                if (ParentQuestionId != null) { return RedirectToAction("Details", new { id = ParentQuestionId }); }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOption(QuestionOption viewModel)
        {
            if (!ModelState.IsValid) { return View(); }
            _context.QuestionOptions.Add(viewModel);
            _context.SaveChanges();
            return RedirectToAction("Details", new { id = viewModel.QuestionId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteOption(int? id)
        {
            if (id == null) { return Json(new { success = false }, JsonRequestBehavior.AllowGet); }
            var option = _context.QuestionOptions.Find(id);
            if (option == null) { return Json(new { success = false }, JsonRequestBehavior.AllowGet); }
            _context.QuestionOptions.Remove(option);
            _context.SaveChanges();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> AddNestedQuestion(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            var question = await _context.Questions.Where(q => q.Id == id).FirstOrDefaultAsync();
            if (question == null) { return RedirectToAction("Index"); }
            var viewModel = new Question
            {
                Id = question.Id,
                CategoryId = question.CategoryId,
                ParentId = question.Id
            };
            ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", question.CategoryId);
            viewModel.Children = _context.Questions.Where(q => q.ParentId == id).ToList();

            var FormInputs = await formInputRepository.GetAllAsync();
            ViewBag.SelectFormInputId = new SelectList(FormInputs, "Id", "FormInputName");

            ViewBag.Options = await OptionRepository.GetAllAsync();
            ViewBag.FormInputs = FormInputs;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddNestedQuestion(Question viewModel)
        {
            if (!ModelState.IsValid) { return RedirectToAction("Index"); }
            var question = await _context.Questions.Where(q => q.Id == viewModel.Id).FirstOrDefaultAsync();
            if (question == null) { return RedirectToAction("Index"); }
            _context.Questions.Add(viewModel);
            _context.SaveChanges();
            TempData["Success"] = "Successfully added";
            return RedirectToAction("AddNestedQuestion", new { id = viewModel.Id });
        }
    }
}

VaccineSurvey.Web/Views/Categories/Create.cshtml
@model VaccineSurvey.Model.Category
@{
    ViewBag.Title = "Add Category";
}
<style>
    input,
    select,
    textarea {
        max-width: 400px;
    }
</style>
<div class="card dashboard">
    <div class="service_list">
        <h4>@ViewBag.Title</h4>
        <div class="container">
            @if (TempData["Success"] != null)
            {
                <div class="row mt-2"><div class="col-sm-12"><div class="alert alert-success" role="alert">@TempData["Success"]</div></div></div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="row mt-2"><div class="col-sm-12"><div class="alert alert-danger" role="alert">@TempData["Error"]</div></div></div>
            }
            <div class="row mt-2 text-left">
                <div class="col-sm-12">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "font-weight-bold required" })
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_ZH, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_ZH, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_FR, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_FR, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_IT, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_IT, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_PT, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_PT, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_ES, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_ES, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_RU, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_RU, new { htmlAttributes = new { @class = "form-control" } })
                        </div> 
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_ES, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_ES, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_RU, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_RU, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_UR, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_UR, new { htmlAttributes = new { @class = "form-control" } })
                        </div> 
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_HI, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_HI, new { htmlAttributes = new { @class = "form-control" } })
                        </div> 
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_MR, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_MR, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sequence, new { @class = "font-weight-bold required" })
                            @Html.EditorFor(model => model.Sequence, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        </div>

                        <div class="form-group">
                            <div class="checkbox">
                                @Html.CheckBoxFor(m => m.IsVisible)
                                @Html.LabelFor(m => m.IsVisible)
                            </div>
                        </div> 
                        <div class="form-group">
                            <button type="submit" class="btn btn-sm btn-success"><span class="fa fa-floppy-o"></span> Save</button>
                            <a title="Cancel" href="@Url.Action("Index")" class="btn btn-sm btn-dark">Cancel</a>
                        </div>  
                    }
                </div>
            </div>
        </div>
    </div>
</div>

VaccineSurvey.Web/Views/Categories/Delete.cshtml
@model VaccineSurvey.Model.Category
@{
    ViewBag.Title = "Delete Category";
}
<style>
    input,
    select,
    textarea {
        max-width: 400px;
    }
</style>
<div class="card dashboard">
    <div class="service_list">
        <h4>@ViewBag.Title</h4>
        <div class="container">
            @if (TempData["Success"] != null)
            {
                <div class="row mt-2"><div class="col-sm-12"><div class="alert alert-success" role="alert">@TempData["Success"]</div></div></div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="row mt-2"><div class="col-sm-12"><div class="alert alert-danger" role="alert">@TempData["Error"]</div></div></div>
            }
            <div class="row mt-2 text-left">
                <div class="col-sm-12">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.Id)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "font-weight-bold required" })
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "font-weight-bold required" })
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_ZH, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_ZH, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_FR, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_FR, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_IT, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_IT, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_PT, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_PT, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_ES, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_ES, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_RU, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_RU, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_ES, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_ES, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_RU, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_RU, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_UR, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_UR, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_HI, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_HI, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name_MR, new { @class = "font-weight-bold" })
                            @Html.EditorFor(model => model.Name_MR, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Sequence, new { @class = "font-weight-bold required" })
                            @Html.EditorFor(model => model.Sequence, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>

                        <div class="form-group"> 
                            <div class="checkbox">
                                @Html.CheckBoxFor(m => m.IsVisible, new { @disabled = "disabled" })
                                @Html.LabelFor(m => m.IsVisible)
                            </div>
                        </div>
                        <div class="form-group" style="color:red">
                            Note: By deleting this category all the records (Questions, Options and Survey) related to this category will be deleted.
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-sm btn-success"><span class="fa fa-trash-o"></span> Delete</button>
                            <a title="Cancel" href="@Url.Action("Index")" class="btn btn-sm btn-dark">Cancel</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

VaccineSurvey.Web/Views/Categories/Index.cshtml
@using VaccineSurvey.Model;
@model List<Category>
@{
    ViewBag.Title = "Categories";
    var Language = UserRoleDetails.GetLanguage();
    var Questions = (List<Question>)ViewBag.Questions;
}
<div class="card dashboard">
    <div class="service_list">
        <h4>
            @ViewBag.Title
            @if (Language == "admin")
            {
                <a href="@Url.Action("Create")" class="btn btn-sm btn-dark pull-right" style="margin-right: 10px;"><span class="fa fa-plus"></span> Add Category</a>
            }
        </h4>
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-sm" id="customTable">
            <thead>
                <tr>
                    <th class="text-left">Name</th>
                    <th class="text-center">Sequence</th>
                    <th class="text-left">Visible</th>
                    <th class="text-right">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-left">@Html.Raw(UserRoleDetails.GetPropValue(item, "Name", Language))</td>
                        <td class="text-center">@item.Sequence</td>
                        <td class="text-left">
                            @if (item.IsVisible)
                            {
                                <span>Visible</span>
                            }
                            else
                            {
                                <span>Not Visible</span>
                            }
                        </td>
                        <td class="text-right">
                            @if (Language == "admin")
                            {
                                <a title="Add Question" href="@Url.Action("Create", "Questions", new { id = item.Id })" class="btn btn-sm btn-success"><span class="fa fa-plus"></span></a>
                                <a title="View All Questions" href="@Url.Action("Index", "Questions", new { id = item.Id })" class="btn btn-sm btn-success"><span class="fa fa-info"></span></a>
                            }
                            else
                            {
                                if (Questions.Where(x => x.CategoryId == item.Id).Count() > 0)
                                {
                                    <a title="View All Questions" href="@Url.Action("Index", "Questions", new { id = item.Id })" class="btn btn-sm btn-success"><span class="fa fa-info"></span></a>
                                }
                            }
                            <a title="Edit Category" href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-sm btn-primary"><span class="fa fa-pencil"></span></a>
                            @if (Language == "admin")
                            {
                                <a title="Delete Category" href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div> 