VaccineSurvey.Web/Controllers/CategoriesController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using VaccineSurvey.Data.Repositories;
using VaccineSurvey.Model;

namespace VaccineSurvey.Web.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly IQuestionRepository questionRepository;

        public CategoriesController(IQuestionRepository questionRepository, ICategoryRepository categoryRepository)
        {
            this.questionRepository = questionRepository;
            this.categoryRepository = categoryRepository;
        }

        public async Task<ActionResult> Index()
        {
            ViewBag.Questions = await questionRepository.GetAllAsync();
            return View(await categoryRepository.GetAllAsync());
        }

        public ActionResult Create()
        {
            if (UserRoleDetails.GetLanguage() == "admin") return View();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Category viewModel)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (ModelState.IsValid)
                {
                    var Succeeded = await categoryRepository.CreateAsync(viewModel);
                    if (Succeeded)
                    {
                        TempData["Success"] = "Category saved successfully.";
                        return RedirectToAction("Create");
                    }
                }
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            var category = await categoryRepository.FindByIdAsync(id);
            if (category == null) { return RedirectToAction("Index"); }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Category viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }

            var Succeeded = await categoryRepository.UpdateAsync(viewModel, UserRoleDetails.GetLanguage());
            if (Succeeded)
            {
                TempData["Success"] = "Category Updated successfully.";
                return RedirectToAction("Edit", new { id = viewModel.Id });
            }

            return RedirectToAction("Edit", new { id = viewModel.Id });
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (id == null) { return RedirectToAction("Index"); }
                var category = await categoryRepository.FindByIdAsync(id);
                if (category == null) { return RedirectToAction("Index"); }
                return View(category);
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? id)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (id == null)
                {
                    TempData["Error"] = "Try again input data error";
                    return RedirectToAction("Index");
                }
                var Succeeded = await categoryRepository.DeleteAsync(id);
                if (Succeeded)
                {
                    TempData["Success"] = "Category deleted successfully";
                    return RedirectToAction("Index");
                }
                TempData["Error"] = "Try again input data error";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

VaccineSurvey.Web/Controllers/ReplaceTextController.cs
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Web.Mvc;
using VaccineSurvey.Data.Repositories;
using VaccineSurvey.Model;

namespace VaccineSurvey.Web.Controllers
{
    [Authorize]
    public class ReplaceTextController : Controller
    {
        private readonly IReplaceTextRepository replaceTextRepository;
        private readonly IUserRepository userRepository;

        public ReplaceTextController(IReplaceTextRepository _replaceTextRepository,
            IUserRepository userRepository) 
        {
            replaceTextRepository = _replaceTextRepository;
            this.userRepository = userRepository;
        } 

        public ActionResult Questions()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Questions(ReplaceText viewModel)
        {
            if (ModelState.IsValid)
            {
                var roleName = await userRepository.GetRolesAsync(User.Identity.GetUserId());
                var Succeeded = await replaceTextRepository.QuestionsAsync(viewModel, roleName);
                if (Succeeded)
                {
                    TempData["Success"] = "Text Replaced Successfully.";
                    return RedirectToAction("Questions");
                }
            }
            TempData["Error"] = "Sorry...! An error occurred.";
            ViewBag.Data = await replaceTextRepository.GetAllAsync();
            return View(viewModel);
        }

        public ActionResult Options()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Options(ReplaceText viewModel)
        {
            if (ModelState.IsValid)
            {
                var roleName = await userRepository.GetRolesAsync(User.Identity.GetUserId());
                var Succeeded = await replaceTextRepository.OptionsAsync(viewModel, roleName);
                if (Succeeded)
                {
                    TempData["Success"] = "Text Replaced Successfully.";
                    return RedirectToAction("Options");
                }
            }
            TempData["Error"] = "Sorry...! An error occurred.";
            ViewBag.Data = await replaceTextRepository.GetAllAsync();
            return View(viewModel);
        }
    }
}

VaccineSurvey.Web/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using VaccineSurvey.Data.Repositories;
using VaccineSurvey.Model;
using VaccineSurvey.ViewModel;
using VaccineSurvey.Web.Models;

namespace VaccineSurvey.Web.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private readonly IAuthRepository authRepository;

        public UsersController(IAuthRepository _AuthRepository) => authRepository = _AuthRepository;

        public UsersController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get { return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>(); }
            private set { _signInManager = value; }
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            ViewBag.User = User.Identity.GetUserId();
            var usersWithRoles = (from user in db.Users
                                  select new
                                  {
                                      Id = user.Id,
                                      FirstName = user.FirstName,
                                      LastName = user.LastName,
                                      Email = user.Email,
                                      RoleNames = (from userRole in user.Roles
                                                   join role in db.Roles on userRole.RoleId
                                                   equals role.Id
                                                   select role.Name).FirstOrDefault()
                                  }).ToList().Select(p => new Users_in_Role_ViewModel()
                                  {
                                      Id = p.Id,
                                      FirstName = p.FirstName,
                                      LastName = p.LastName,
                                      Email = p.Email,
                                      UserRoles = p.RoleNames
                                  });

            return View(usersWithRoles);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            RegisterViewModel viewModel = new RegisterViewModel();
            ViewBag.Name = new SelectList(db.Roles.OrderBy(x => x.Name).ToList(), "Name", "Name");
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel viewModel)
        {
            string errors = "Sorry an error occured. Try again.";
            if (ModelState.IsValid)
            {
                var appUser = new ApplicationUser
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Email = viewModel.Email,
                    UserName = viewModel.Email,
                    CreatedDate = DateTime.Now
                };

                var result = await UserManager.CreateAsync(appUser, viewModel.Password);
                if (result.Succeeded)
                {
                    try
                    {
                        await UserManager.AddToRoleAsync(appUser.Id, viewModel.UserRoles);
                    }
                    catch (Exception ex)
                    {
                        errors = ex.Message;
                    }
                    TempData["Success"] = "User saved successfully";
                    return RedirectToAction("Create");
                }
            }
            else
            {
                errors = "";
                foreach (ModelState modelState in ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errors += error.ErrorMessage + "<br/>";
                    }
                }
            }
            ViewBag.Name = new SelectList(db.Roles.OrderBy(x => x.Name).ToList(), "Id", "Name");
            TempData["Error"] = errors;
            return View(viewModel);
        }

        public async Task<ActionResult> EditProfile()
        {

            var appUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (appUser == null) { return RedirectToAction("Error"); }

            var viewModel = new EditProfileViewModel
            {
                FirstName = appUser.FirstName,
                LastName = appUser.LastName,
                Email = appUser.Email
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditProfile(EditProfileViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }
            var appUser = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (appUser == null) { return RedirectToAction("Error"); }
            appUser.FirstName = viewModel.FirstName;
            appUser.LastName = viewModel.LastName;

            var result = await UserManager.UpdateAsync(appUser);
            if (result.Succeeded)
            {
                TempData["Success"] = "Profile Successfully Updated.";
            }
            else
            {
                TempData["Error"] = "Sorry...! Please try again.";
            }
            return RedirectToAction("EditProfile");
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(string Id)
        {
            var appUser = await UserManager.FindByIdAsync(Id);
            if (appUser == null) { return RedirectToAction("Error"); }

            var usersWithRoles = (from user in db.Users
                                  select new
                                  {
                                      Id = user.Id,
                                      Username = user.UserName,
                                      FirstName = user.FirstName,
                                      LastName = user.LastName,
                                      Email = user.Email,
                                      RoleNames = (from userRole in user.Roles
                                                   join role in db.Roles on userRole.RoleId
                                                   equals role.Id
                                                   select role.Name).FirstOrDefault()
                                  }).Where(x => x.Id == appUser.Id).Select(p => new Users_in_Role_ViewModel()
                                  {
                                      Id = p.Id,
                                      FirstName = p.FirstName,
                                      LastName = p.LastName,
                                      Email = p.Email,
                                      UserRoles = p.RoleNames
                                  });

            ViewBag.Name = new SelectList(db.Roles.OrderBy(x => x.Name).ToList(), "Name", "Name");
            return View(usersWithRoles.FirstOrDefault());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Users_in_Role_ViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }
            var appUser = await UserManager.FindByIdAsync(viewModel.Id);
            if (appUser == null) { return RedirectToAction("Error"); }
            appUser.FirstName = viewModel.FirstName;
            appUser.LastName = viewModel.LastName;

            var result = await UserManager.UpdateAsync(appUser);
            if (result.Succeeded)
            {
                var oldRoleId = appUser.Roles.SingleOrDefault();
                if (oldRoleId != null)
                {
                    var oldRoleName = db.Roles.SingleOrDefault(r => r.Id == oldRoleId.RoleId).Name;

                    if (oldRoleName != viewModel.UserRoles)
                    {
                        await UserManager.RemoveFromRoleAsync(viewModel.Id, oldRoleName);
                        await UserManager.AddToRoleAsync(viewModel.Id, viewModel.UserRoles);
                    }
                }
                else
                    await UserManager.AddToRoleAsync(viewModel.Id, viewModel.UserRoles);
                TempData["Success"] = "User updated successfully.";
            }
            else
            {
                TempData["Error"] = "Sorry...! Please try again.";
            }
            ViewBag.Name = new SelectList(db.Roles.OrderBy(x => x.Name).ToList(), "Name", "Name");
            return RedirectToAction("Edit", viewModel);
        }

        public ActionResult ChangePassword() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

VaccineSurvey.Web/Views/Shared/_Layout.cshtml
@using VaccineSurvey.Web.Resources
@{
    var Language = UserRoleDetails.GetLanguage();
    var fulllang = new LanguageMangager().GetCurrentLanguage();
    var dir = LanguageMangager.GetLanguage(fulllang).LanguageDirection;
    //if (dir != "rtl") { dir = ""; }

    string lang = fulllang.Split('-')[0];

    ViewBag.meta_og_image = Html.Raw(Resource.meta_og_image);
    ViewBag.meta_title = Html.Raw(Resource.meta_title);
    ViewBag.meta_site = Html.Raw(Resource.meta_site);
    ViewBag.meta_description = Html.Raw(Resource.meta_description);
    ViewBag.meta_keywords = Html.Raw(Resource.meta_keywords);
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="@lang" xml:lang="@lang">
<head>
    <meta charset='utf-8' />
    <meta http-equiv="content-language" content="@lang" />

    <meta name="" content="HTML,CSS,XML,JavaScript" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="twitter:image" content="@ViewBag.meta_og_image" />
    <title>@Html.Raw(ViewBag.Title)</title>

    <meta name="title" content="@ViewBag.meta_title" />
    <meta name="keywords" content="@ViewBag.meta_keywords" />
    <meta name="description" content="@ViewBag.meta_description" />

    <meta property="og:title" content="@ViewBag.meta_title" />
    <meta property="og:description" content="@ViewBag.meta_description" />
    <meta property="og:url" content="https://survey.pregistry.com/@lang/" />
    <meta property="og:image:secure_url" content="@ViewBag.meta_og_image" />
    <meta property="og:image" content="@ViewBag.meta_og_image" />

    <link rel="canonical" href="https://survey.pregistry.com/@lang/" />

    <meta name="twitter:url" content="https://survey.pregistry.com/@lang/" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@ViewBag.meta_site" />
    <meta name="twitter:title" content="@ViewBag.meta_title" />
    <meta name="twitter:description" content="@ViewBag.meta_description" />

    <link rel="icon" href="~/fav/favicon.ico" />
    <link href="~/Content/style.css?v=3" rel="stylesheet" />
    <link href="~/Content/custom.css?v=3" rel="stylesheet" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script src="https://www.googletagmanager.com/gtag/js?id=G-JTSSEBCM06" async="async"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'G-V7JZ2H5RXN');
    </script>
    <!-- Facebpooku Pixel Code -->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return; n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
            n.queue = []; t = b.createElement(e); t.async = !0;
            t.src = v; s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '779541489501324');
        fbq('track', 'PageView');
    </script>
    <noscript>
        <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=779541489501324&ev=PageView&noscript=1" />
    </noscript>
    <!-- End Facebook Pixel Code -->
    <link rel="alternate" hreflang="x-default" href="https://survey.pregistry.com" />
    @foreach (var i in LanguageMangager.AvailableLanguages)
    {
        <link rel="alternate" hreflang="@i.LanguageCultureNameS" href="https://survey.pregistry.com/@i.LanguageCultureNameS" />

    }
    @if (dir == "rtl")
    {
        <style>
            .classy-navbar .nav-brand {
                margin-right: 0;
                padding-right: 0;
                border-right: 0;
                margin-left: 20px;
                padding-left: 20px;
                border-left: 2px solid #5bbc2e;
            }
            .classy-navbar .nav-brand2 {
                margin-left: 0;
                padding-left: 0;
                border-left: 0;
                margin-right: 20px;
                padding-right: 20px;
                border-right: 2px solid #5bbc2e;
            }


            div.text-right, .progress-bar {
                text-align: left !important;
            }

            div.text-left, .mtrh {
                text-align: right !important;
            }

            .progress-bar {
                padding-left: 5px;
            }

            .mtable .mrh > span:after {
                right: unset !important;
                left: -17px;
            }

            @@media screen and (min-width: 768px) {
                .mth:last-child, .mtd:last-child {
                    border-right: 1px solid #dee2e6;
                }

                .mth:first-child, .mtd:first-child {
                    border-right: none;
                }
            }


            @@media only screen and (max-width: 767px) {
                .classy-navbar .nav-brand {
                    margin-right: 0;
                    padding-right: 0;
                    margin-left: 10px;
                    padding-left: 10px;
                }

                .classy-navbar .nav-brand2 {
                    margin-left: 0;
                    padding-left: 0;
                    margin-right: 10px;
                    padding-right: 10px;
                }

                .mrh {
                    padding-right: 0 !important;
                    padding-left: 10px;
                }
            }
        </style>
    }
    <style>
        .classynav #nav a {
            border-top: 1px solid #e0e0e0 !important;
        }

            .classynav #nav a:first-child {
                border-top: 0 solid #e0e0e0 !important;
            }

        .logostyle {
            width: 100%;
            max-width: 120px;
        }

        @@media only screen and (min-width: 991px) {
            .logostyle {
                width: 100%;
                max-width: 180px;
                margin-top: 10px;
            }

            .width-lg-100 {
                width: 50% !important; 
            }

            .nav-brand {
                border-right: 2px solid #5bbc2e;
            }
            .nav-brand2 {
                border-left: 2px solid #5bbc2e;
            }
        }
    </style>
</head>
<body>
    <div id="preloader"><div class="preload-content"><div id="dream-load"></div></div></div>
    <header class="header-area">
        <div class="classy-nav-container light">
            <div class="container" dir="@dir">
                <div class="row" style="margin-top: 10px;">
                    <div class="nav-brand col-lg-2 col-md-3 col-sm-6 col-xs-6 col-6"><img src="@Resource.site_logo" class="logostyle" style="" alt="logo" /></div>
                    <div class="col-lg-7 col-md-6 col-sm-12 col-xs-12 col-12 order-lg-2 order-md-2 order-sm-3 order-3"><h3 class="header-line">@Resource.SiteTitle</h3></div>
                    <div class="nav-brand2 col-lg-3 col-md-3 col-sm-6 col-xs-6 col-6 order-lg-3 order-md-3 order-sm-2 order-2"><img src="@Resource.site_logo2" alt="logo" /></div>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <nav class="classy-navbar light justify-content-between clearfix">
                        <div style="width: 50%;">@UserRoleDetails.GetUserName()</div>
                        <div class="classy-navbar-toggler demo" style="width: 50%;text-align: right;"><span class="navbarToggler"><span></span><span></span><span></span></span></div>
                        <div class="classy-menu width-lg-100">
                            <div class="classycloseIcon"><div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div></div>
                            <div class="classynav float-lg-right">
                                <ul id="nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Menu</a>
                                        <div class="dropdown-menu">
                                            @if (Language == "admin")
                                            {
                                                <a class="dropdown-item" href="@Url.Action("Index", "Dashboard")">Dashboard</a>
                                                <a class="dropdown-item" href="@Url.Action("Country", "Dashboard")">Frequency By Country</a>
                                                <a class="dropdown-item" href="@Url.Action("CountryFeedback", "Dashboard")">FEEDBACK BY PARTICIPANT</a>
                                                <a class="dropdown-item" href="@Url.Action("New", "Dashboard")">New Dashboard</a>
                                                <a class="dropdown-item" href="@Url.Action("Index", "Categories")">Categories</a>
                                                <a class="dropdown-item" href="@Url.Action("Index", "Questions")">Questions</a>
                                                <a class="dropdown-item" href="@Url.Action("Index", "Home")">Survey</a>
                                                <a class="dropdown-item" href="@Url.Action("Index", "Users")">Users</a>
                                                <a class="dropdown-item" href="@Url.Action("Index", "RoleManagement")">Role Management</a>
                                                <a class="dropdown-item" href="@Url.Action("Index", "ReplaceText")">Replace Text</a>
                                                <a class="dropdown-item" href="@Url.Action("EditProfile", "Users")">Edit Profile</a>
                                            }
                                            else
                                            {
                                                <a class="dropdown-item" href="@Url.Action("Index", "Categories")">Categories</a>
                                            
                                                <a class="dropdown-item" href="@Url.Action("Questions", "ReplaceText")">Replace Questions text</a>
                                                <a class="dropdown-item" href="@Url.Action("Options", "ReplaceText")">Replace Options Text</a>
                                                <a class="dropdown-item" href="@Url.Action("EditProfile", "Users")">Edit Profile</a>
                                            }
                                        </div>
                                    </li>
                                </ul>
                                @Html.Partial("_LoginPartial")
                            </div>
                        </div>
                    </nav>
                }
            </div>
        </div>
    </header>
    <section class="corona_form"><div class="container" dir="@dir">@RenderBody()</div></section>
    <footer><div class="container text-center"><p>©@DateTime.Now.Year @Resource.FooterText</p></div></footer>
    <div id="widget">
        <div id="LanguageS">
            <ul>
                @foreach (var i in LanguageMangager.AvailableLanguages)
                {
                    if (i.LanguageCultureNameS != lang)
                    {
                        <li data-locale="@i.LanguageCultureNameS" title="@i.LanguageFullName">@i.LanguageFullName</li>
                    }
                }
            </ul>
        </div>
        <div id="current">
            <ul>
                @{
                    var l = LanguageMangager.AvailableLanguages.Where(x => x.LanguageCultureNameS == lang).FirstOrDefault();
                    if (l != null)
                    {
                        <li data-locale="@l.LanguageCultureNameS" title="@l.LanguageFullName">@l.LanguageFullName</li>
                    }
                    else
                    {
                        <li data-locale="en" title="English">English</li>
                    }
                }
            </ul>
        </div>
    </div>
    <input type="hidden" name="LeavePageMessage" id="LeavePageMessage" value="@Resource.LeavePageMessage.Replace("'", @"\'")" />
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/popper.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/plugins.js?v=7"></script>
    @RenderSection("scripts", required: false)
</body>
</html>