VaccineSurvey.Web/Controllers/LoopQuestionsController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using VaccineSurvey.Data.Repositories;
using VaccineSurvey.Model;

namespace VaccineSurvey.Web.Controllers
{
    [Authorize]
    public class LoopQuestionsController : Controller
    {
        private readonly IQuestionRepository questionRepository;
        private readonly IFormInputRepository formInputRepository;
        private readonly ICategoryRepository categoryRepository;
        public LoopQuestionsController(IQuestionRepository questionRepository, IFormInputRepository formInputRepository, ICategoryRepository categoryRepository)
        {
            this.questionRepository = questionRepository;
            this.formInputRepository = formInputRepository;
            this.categoryRepository = categoryRepository;
        }

        public async Task<ActionResult> Edit(int? id, int? parentQuestionId)
        {
            if (id == null) { return RedirectToAction("Error"); }
            var model = await questionRepository.FindByIdAsync(id);
            if (model == null) { return RedirectToAction("Error"); }
            ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", model.FormInputId);
            ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", model.CategoryId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Question viewModel)
        { 
            if (!ModelState.IsValid) { return View(viewModel); }
            var Succeeded = await questionRepository.UpdateAsync(viewModel, UserRoleDetails.GetLanguage());
            if (!Succeeded) { return RedirectToAction("Error"); }
            else TempData["Success"] = "Successfully Updated.";

            return RedirectToAction("Edit", new { id = viewModel.Id });
        }

        public async Task<ActionResult> Delete(int? id, int? parentQuestionId)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (id == null) { return RedirectToAction("Index"); }
                var viewModel = await questionRepository.FindByIdAsync(id);
                if (viewModel == null) { return RedirectToAction("Index"); }
                ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", viewModel.FormInputId);
                ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", viewModel.CategoryId);
                return View(viewModel);
            }
            return RedirectToAction("Index", "Questions");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? Id, int? ParentQuestionId)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (Id == null) { return RedirectToAction("Index"); }
                var Succeeded = await questionRepository.DeleteAsync(Id);
                if (!Succeeded) { return RedirectToAction("Index"); }
                if (ParentQuestionId != null) { return RedirectToAction("AddNestedQuestion", "Questions", new { id = ParentQuestionId }); }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index", "Questions");
        }
    }
}

VaccineSurvey.Web/Controllers/QuestionsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using VaccineSurvey.Data.Repositories;
using VaccineSurvey.Model;

namespace VaccineSurvey.Web.Controllers
{
    [Authorize]
    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();
        private readonly IQuestionRepository questionRepository;
        private readonly IOptionRepository OptionRepository;
        private readonly IFormInputRepository formInputRepository;
        private readonly ICategoryRepository categoryRepository;

        public QuestionsController(IQuestionRepository questionRepository, IFormInputRepository formInputRepository, ICategoryRepository categoryRepository, IOptionRepository OptionRepository)
        {
            this.OptionRepository = OptionRepository;
            this.questionRepository = questionRepository;
            this.formInputRepository = formInputRepository;
            this.categoryRepository = categoryRepository;
        }

        public async Task<ActionResult> Index(int? id)
        {
            IEnumerable<Question> questions = null;
            if (id != null && id > 0) { questions = await categoryRepository.GetQuestionsAsync(id); }
            if (questions != null && questions.Count() > 0) { }
            else { questions = await questionRepository.GetAllAsync(); }
            ViewBag.FormInputs = await formInputRepository.GetAllAsync();
            ViewBag.Options = await OptionRepository.GetAllAsync();
            ViewBag.ChildQuestions= await questionRepository.GetChildQuestion();
            return View(questions);
        }

        public async Task<ActionResult> Create(int? id)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                int categoryId = 0;
                if (id != null) { categoryId = (int)id; }
                ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", categoryId);
                ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName");
                var model = new Question
                {
                    IsRequired = true,
                    Sequence = 0
                };
                return View(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Question viewModel)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", viewModel.CategoryId);
                ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", viewModel.FormInputId);
                if (!ModelState.IsValid) { return View(viewModel); }
                var questionId = await questionRepository.CreateAsync(viewModel);
                if (questionId == 0)
                {
                    TempData["Error"] = "Try again input data error";
                    return RedirectToAction("Create", viewModel);
                }
                TempData["Success"] = "Question Saved successfully.";
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int? id, int? parentQuestionId)
        {
            if (id == null) { return RedirectToAction("Error"); }
            var model = await questionRepository.FindByIdAsync(id);
            if (model == null) { return RedirectToAction("Error"); }
            ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", model.FormInputId);
            ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", model.CategoryId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Question viewModel)
        {
            ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", viewModel.FormInputId);
            ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", viewModel.CategoryId);

            if (!ModelState.IsValid) { return View(viewModel); }
            var Succeeded = await questionRepository.UpdateAsync(viewModel, UserRoleDetails.GetLanguage());
            if (!Succeeded) { return RedirectToAction("Error"); }
            else { TempData["Success"] = "Question Updated successfully."; }
            return RedirectToAction("Edit", new { id = viewModel.Id });
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            var viewModel = await questionRepository.DetailsAsync(id);
            if (viewModel == null) { return RedirectToAction("Index"); }

            viewModel.ChildQuestions = await _context.Questions.Include(q => q.Children).Where(q => q.ParentId == id).ToListAsync();
            ViewBag.DataModel = viewModel;
            ViewBag.FormInputs = await formInputRepository.GetAllAsync();
            return View(new QuestionOption() { QuestionId = (int)id });
        }

        public async Task<ActionResult> Delete(int? id, int? parentQuestionId)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (id == null) { return RedirectToAction("Index"); }
                var viewModel = await questionRepository.FindByIdAsync(id);
                if (viewModel == null) { return RedirectToAction("Index"); }
                ViewBag.SelectFormInputId = new SelectList(await formInputRepository.GetAllAsync(), "Id", "FormInputName", viewModel.FormInputId);
                ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", viewModel.CategoryId);
                return View(viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int? Id, int? ParentQuestionId)
        {
            if (UserRoleDetails.GetLanguage() == "admin")
            {
                if (Id == null) { return RedirectToAction("Index"); }
                var Succeeded = await questionRepository.DeleteAsync(Id);
                if (!Succeeded) { return RedirectToAction("Index"); }
                if (ParentQuestionId != null) { return RedirectToAction("Details", new { id = ParentQuestionId }); }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOption(QuestionOption viewModel)
        {
            if (!ModelState.IsValid) { return View(); }
            _context.QuestionOptions.Add(viewModel);
            _context.SaveChanges();
            return RedirectToAction("Details", new { id = viewModel.QuestionId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteOption(int? id)
        {
            if (id == null) { return Json(new { success = false }, JsonRequestBehavior.AllowGet); }
            var option = _context.QuestionOptions.Find(id);
            if (option == null) { return Json(new { success = false }, JsonRequestBehavior.AllowGet); }
            _context.QuestionOptions.Remove(option);
            _context.SaveChanges();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> AddNestedQuestion(int? id)
        {
            if (id == null) { return RedirectToAction("Index"); }
            var question = await _context.Questions.Where(q => q.Id == id).FirstOrDefaultAsync();
            if (question == null) { return RedirectToAction("Index"); }
            var viewModel = new Question
            {
                Id = question.Id,
                CategoryId = question.CategoryId,
                ParentId = question.Id
            };
            ViewBag.SelectCategoryId = new SelectList(await categoryRepository.GetAllAsync(), "Id", "Name", question.CategoryId);
            viewModel.Children = _context.Questions.Where(q => q.ParentId == id).ToList();

            var FormInputs = await formInputRepository.GetAllAsync();
            ViewBag.SelectFormInputId = new SelectList(FormInputs, "Id", "FormInputName");

            ViewBag.Options = await OptionRepository.GetAllAsync();
            ViewBag.FormInputs = FormInputs;
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddNestedQuestion(Question viewModel)
        {
            if (!ModelState.IsValid) { return RedirectToAction("Index"); }
            var question = await _context.Questions.Where(q => q.Id == viewModel.Id).FirstOrDefaultAsync();
            if (question == null) { return RedirectToAction("Index"); }
            _context.Questions.Add(viewModel);
            _context.SaveChanges();
            TempData["Success"] = "Successfully added";
            return RedirectToAction("AddNestedQuestion", new { id = viewModel.Id });
        }
    }
}

VaccineSurvey.Web/Views/Questions/AddNestedQuestion.cshtml
@using VaccineSurvey.Model;
@model Question
@{
    ViewBag.Title = "Child Questions";
    var FormInputs = (List<FormInput>)ViewBag.FormInputs;

    var Language = UserRoleDetails.GetLanguage();
    var Role = UserRoleDetails.GetRole();
    var QuestionOption = (List<QuestionOption>)ViewBag.Options;
}
<style>
    input,
    select,
    textarea {
        max-width: 800px;
    }
</style>
<div class="card dashboard">
    <div class="service_list">
        <h4>@ViewBag.Title</h4>
        <div class="container">
            @if (TempData["Success"] != null)
            {
                <div class="row mt-2"><div class="col-sm-12"><div class="alert alert-success" role="alert">@TempData["Success"]</div></div></div>
            }
            @if (TempData["Error"] != null)
            {
                <div class="row mt-2"><div class="col-sm-12"><div class="alert alert-danger" role="alert">@TempData["Error"]</div></div></div>
            }
            <div class="row mt-2 text-left">
                <div class="col-sm-12">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.HiddenFor(model => model.ParentId)
                        if (Language == "admin")
                        {
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_ZH, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_ZH, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_FR, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_FR, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_IT, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_IT, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_PT, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_PT, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_ES, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_ES, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_RU, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_RU, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_ES, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_ES, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_RU, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_RU, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_UR, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_UR, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_HI, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_HI, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name_MR, new { @class = "font-weight-bold" })
                                @Html.EditorFor(model => model.Name_MR, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Sequence, new { @class = "font-weight-bold required" })
                                @Html.EditorFor(model => model.Sequence, new { htmlAttributes = new { @class = "form-control" } })
                            </div>

                            <div class="form-group">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(m => m.IsVisible)
                                    @Html.LabelFor(m => m.IsVisible)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.CategoryId, new { @class = "font-weight-bold required" })
                                @Html.DropDownList("CategoryId", (IEnumerable<SelectListItem>)ViewBag.SelectCategoryId, "(None)", new { @class = "form-control", @required = "required" })
                                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.FormInputId, new { @class = "font-weight-bold required" })
                                @Html.DropDownList("FormInputId", (IEnumerable<SelectListItem>)ViewBag.SelectFormInputId, "(None)", new { @class = "form-control", @required = "required" })
                                @Html.ValidationMessageFor(model => model.FormInputId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.CheckBoxFor(m => m.IsRequired)
                                @Html.LabelFor(m => m.IsRequired)
                            </div>
                        }
                        else
                        {
                            <div class="form-group">
                                <label class="font-weight-bold">Category</label>
                                <input class="form-control disabled text-box single-line" disabled="disabled" type="text" value="@Model.Name">
                                @Html.HiddenFor(model => model.Name)
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold" for="Name_@Language.ToUpper()">Category @Role</label>
                                <input class="form-control text-box single-line" id="Name_@Language.ToUpper()" name="Name_@Language.ToUpper()" type="text" value="@Html.Raw(UserRoleDetails.GetPropValue(Model, "Name", Language))">
                            </div>
                        }
                        <div class="form-group">
                            <button type="submit" class="btn btn-sm btn-success"><span class="fa fa-floppy-o"></span> Save</button>
                            <a title="Cancel" href="@Url.Action("Index")" class="btn btn-sm btn-dark">Cancel</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@if (Model.Children.Count > 0)
{
    <div class="card dashboard">
        <div class="service_list">
            <div class="table-responsive">
                <table class="table table-hover table-sm" id="customTable">
                    <thead>
                        <tr>
                            <th class="text-left">Question</th>
                            <th class="text-center">Sequence</th>
                            <th class="text-left">Required</th>
                            <th class="text-left">Visible</th>
                            <th class="text-left">Input Type</th>
                            <th class="text-right" width="20%">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Children)
                        {
                            var inputType = FormInputs.Where(x => x.Id == item.FormInputId).FirstOrDefault().FormInputName;
                            <tr>
                                <td class="text-left">@Html.Raw(UserRoleDetails.GetPropValue(item, "Name", Language))</td>
                                <td class="text-center">@item.Sequence</td>
                                <td class="text-left">
                                    @if (item.IsRequired)
                                    {
                                        <span>Required</span>
                                    }
                                    else
                                    {
                                        <span>Not Required</span>
                                    }
                                </td>
                                <td class="text-left">
                                    @if (item.IsVisible)
                                    {
                                        <span>Visible</span>
                                    }
                                    else
                                    {
                                        <span>Not Visible</span>
                                    }
                                </td>
                                <td class="text-left">@inputType</td>
                                <td class="text-right">
                                    @if (Language == "admin")
                                    {
                                        <a title="Options" target="_blank" href="@Url.Action("Details", new { id = item.Id })" class="btn btn-success btn-sm"><span class="fa fa-list-ul"></span></a>
                                    }
                                    else
                                    {
                                        if (QuestionOption.Where(x => x.QuestionId == item.Id).Count() > 0)
                                        {
                                            <a title="Options" target="_blank" href="@Url.Action("Details", new { id = item.Id })" class="btn btn-success btn-sm"><span class="fa fa-list-ul"></span></a>
                                        }
                                    }
                                    <a title="Edit Question" href="@Url.Action("Edit", "LoopQuestions", new { id = item.Id, parentQuestionId = Model.Id })" class="btn btn-primary btn-sm"><span class="fa fa-pencil"></span></a>
                                    @if (Language == "admin")
                                    {
                                        <a title="Delete Question" href="@Url.Action("Delete", "LoopQuestions", new { id = item.Id, parentQuestionId = Model.Id })" class="btn btn-danger btn-sm"><span class="fa fa-trash"></span></a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
@section Scripts {
    <script type="text/javascript">
        (function ($) { window.setTimeout(function () { $(".alert").fadeTo(500, 0).slideUp(500, function () { $(this).remove(); }); }, 2000); })(jQuery);
    </script>
}

VaccineSurvey.Web/Views/Questions/Index.cshtml
@using VaccineSurvey.Model;
@model IEnumerable<Question>
@{
    ViewBag.Title = "Questions Backend";
    var FormInputs = (List<FormInput>)ViewBag.FormInputs;
    var Language = UserRoleDetails.GetLanguage();
    var QuestionOption = (List<QuestionOption>)ViewBag.Options;
    var ChildQuestions = (List<Question>)ViewBag.ChildQuestions;
}
<div class="card dashboard">
    <div class="service_list">
        <h4>
            @ViewBag.Title
            @if (Language == "admin")
            {
                <a href="@Url.Action("Create", "Questions")" class="btn btn-sm btn-dark pull-right" style="margin-right: 10px;"><span class="fa fa-plus"></span> Add Questions</a>
            }
        </h4>
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-sm" id="customTable">
            <thead>
                <tr>
                    <th class="text-left">Question</th>
                    <th class="text-center">Sequence</th>
                    <th class="text-left">Required</th>
                    <th class="text-left">Visible</th>
                    <th class="text-left">Input Type</th>
                    <th class="text-right" width="20%">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    var inputType = FormInputs.Where(x => x.Id == item.FormInputId).FirstOrDefault().FormInputName;
                    <tr>
                        <td class="text-left">@Html.Raw(UserRoleDetails.GetPropValue(item, "Name", Language))</td>
                        <td class="text-center">@item.Sequence</td>
                        <td class="text-left">
                            @if (item.IsRequired)
                            {
                                <span>Required</span>
                            }
                            else
                            {
                                <span>Not Required</span>
                            }
                        </td>
                        <td class="text-left">
                            @if (item.IsVisible)
                            {
                                <span>Visible</span>
                            }
                            else
                            {
                                <span>Not Visible</span>
                            }
                        </td>
                        <td class="text-left">@inputType</td>
                        <td class="text-right">
                            @if (Language == "admin")
                            {
                                <a title="Options" href="@Url.Action("Details", "Questions", new { id = item.Id })" class="btn btn-sm btn-success"><span class="fa fa-list-ul"></span></a>
                                <a title="Child Questions" href="@Url.Action("AddNestedQuestion", "Questions", new { id = item.Id })" class="btn btn-sm btn-success"><span class="fa fa-plus"> Child</span></a>
                            }
                            else
                            {
                                if (QuestionOption.Where(x => x.QuestionId == item.Id).Count() > 0)
                                {
                                    <a title="Options" href="@Url.Action("Details", "Questions", new { id = item.Id })" class="btn btn-sm btn-success"><span class="fa fa-list-ul"></span></a>
                                }
                                if (ChildQuestions.Where(x => x.ParentId == item.Id).Count() > 0)
                                {
                                    <a title="Child Questions" href="@Url.Action("AddNestedQuestion", "Questions", new { id = item.Id })" class="btn btn-sm btn-success"><span class="fa fa-plus"> Child</span></a>
                                }
                            }
                            <a title="Edit Question" href="@Url.Action("Edit", "Questions", new { id = item.Id })" class="btn btn-sm btn-primary"><span class="fa fa-pencil"></span></a>
                            @if (Language == "admin")
                            {
                                <a title="Delete Question" href="@Url.Action("Delete","Questions", new { id = item.Id })" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div> 